name: CI of gha project

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v4
      - name: docker setup
        run: docker/setup-buildx-action@v4
